from __future__ import annotations

import base64
import binascii
import hashlib
from uuid import UUID, uuid4

import boto3
from botocore.config import Config
from fastapi import HTTPException, status

from app.core.config import Settings
from app.models.asset import Asset
from app.models.enums import AssetType
from app.models.image_generation_job import ImageGenerationJob
from app.models.image_worker import ImageWorker
from app.repositories.image_worker_repository import ImageWorkerRepository
from app.schemas.image_workers import ImageWorkerRegisterRequest


class ImageWorkerService:
    MAX_IMAGE_BYTES = 20 * 1024 * 1024

    def __init__(self, repository: ImageWorkerRepository, settings: Settings) -> None:
        self.repository = repository
        self.settings = settings

    def register(self, payload: ImageWorkerRegisterRequest) -> ImageWorker:
        return self.repository.register(name=payload.name, runtime=payload.runtime, model=payload.model)

    def get_worker(self, worker_id: UUID) -> ImageWorker:
        worker = self.repository.get(worker_id)
        if not worker:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Image worker not found.")
        return worker

    def heartbeat(self, worker_id: UUID) -> ImageWorker:
        return self.repository.heartbeat(self.get_worker(worker_id))

    def claim_next_job(self, worker_id: UUID) -> ImageGenerationJob | None:
        worker = self.get_worker(worker_id)
        priorities = tuple(item.strip() for item in self.settings.image_worker_runtime_priority.split(",") if item.strip())
        return self.repository.claim_next_job(worker, runtime_priority=priorities, online_timeout_seconds=self.settings.image_worker_online_timeout_seconds, max_active_jobs=self.settings.image_worker_max_active_jobs)

    def complete_job(self, job_id: UUID, worker_id: UUID, image_base64: str, mime_type: str, seed: int | None) -> ImageGenerationJob:
        job = self._get_claimed_job(job_id, worker_id)
        image_bytes = self._decode_image(image_base64)
        storage_path = self._storage_path(job, mime_type)
        self._upload(storage_path, image_bytes, mime_type)
        checksum = hashlib.sha256(image_bytes).hexdigest()
        public_url = self._public_url(storage_path)
        asset = Asset(project_id=job.project_id, asset_type=AssetType.IMAGE, name=f"{job.external_id or job.id}-generated", description="Generated by JJ image worker", storage_provider="s3", storage_path=storage_path, public_url=public_url, mime_type=mime_type, size_bytes=len(image_bytes), checksum=checksum, asset_metadata={"image_generation_job_id": str(job.id), "worker_id": str(worker_id), "provider": job.provider, "model": job.model, "seed": seed if seed is not None else job.seed})
        if seed is not None:
            job.seed = seed
        return self.repository.complete_job(job, asset)

    def fail_job(self, job_id: UUID, worker_id: UUID, error: str) -> ImageGenerationJob:
        job = self._get_claimed_job(job_id, worker_id)
        return self.repository.fail_job(job, error)

    def _get_claimed_job(self, job_id: UUID, worker_id: UUID) -> ImageGenerationJob:
        job = self.repository.get_claimed_job(job_id, worker_id)
        if not job:
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Job is not processing or is owned by another worker.")
        return job

    def _decode_image(self, image_base64: str) -> bytes:
        try:
            data = base64.b64decode(image_base64, validate=True)
        except (binascii.Error, ValueError) as exc:
            raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="Invalid image_base64.") from exc
        if not data or len(data) > self.MAX_IMAGE_BYTES:
            raise HTTPException(status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE, detail="Generated image must be between 1 byte and 20 MB.")
        return data

    def _storage_path(self, job: ImageGenerationJob, mime_type: str) -> str:
        extensions = {"image/png": "png", "image/jpeg": "jpg", "image/webp": "webp"}
        extension = extensions.get(mime_type)
        if not extension:
            raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail="Unsupported image MIME type.")
        return f"projects/{job.project_id}/generated-images/{job.id}-{uuid4().hex[:8]}.{extension}"

    def _upload(self, storage_path: str, data: bytes, mime_type: str) -> None:
        client = boto3.client("s3", endpoint_url=self.settings.s3_endpoint_url, aws_access_key_id=self.settings.s3_access_key, aws_secret_access_key=self.settings.s3_secret_key, region_name=self.settings.s3_region, use_ssl=self.settings.s3_use_ssl, config=Config(signature_version="s3v4"))
        client.put_object(Bucket=self.settings.s3_bucket, Key=storage_path, Body=data, ContentType=mime_type)

    def _public_url(self, storage_path: str) -> str:
        base = self.settings.s3_public_endpoint_url.rstrip("/")
        return f"{base}/{self.settings.s3_bucket}/{storage_path}"
